### ISSUE TITLE
Setup MKDOCS for GreenEarthOS repo

### ISSUE THREAD

**Issue by PLoiya** [hackforla/GreenEarthOS#74]
### Overview
we need to setup mkdocs for in order to build a wiki for publicising our project research

### Action Items
- [ ] Install mkdocs into GreenEarthOS repo
- [ ] Document any configurational settings - option/details, in a comment on this issue

### Resources/Instructions
Sample to refer https://brigade.cloud/

**Comment by JasonEb** [comment]
I have setup the GreenEarthOS repo with mkdocks with this [pull request](https://github.com/hackforla/GreenEarthOS/pull/75). Please let me know if there's anything I need to revise and review. 

Mkdocs is a python ` pip` package. It can be installed individually but I opted to start a `requirements.txt` package for future python packages to add to the project.

I have updated the repo readme.md with Installation instructions and requirements. Additionally I added some sample test pages in the `/docs` folder for reference. 

## Usage

Mkdocs requires an `index.md` file in the `docs` folder and a `mkdocs.yml` in the root. To run a local development server, use `mkdocs serve` which will have hot reloading on code changes. 

## Customization

Most of the configuration starts with the `mkdocs.yml` file. For theming, there is

```yml
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "red"
    accent: "blue"
```

Additionally there is a sizable collection of mkdocs themes at https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes.

Thers are the more basic configurations. However there are advanced customizations where one can pull additional css or js files. 

```yml
extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
```

There is a healthy plug-in ecosystem for mkdocs.

```yml
plugins:
  - search
  - awesome-pages
```

These plug-ins are collected here https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins. Notable ones are the translation and localization plug-ins in my opinion. 

Finally there are `markdown_extensions` for additional documentation tools. 
```yml
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
```
These ones are examples of creating code block friendly text, creating diagrams with markdown syntax, or generating a table of contents functionality. Extensions can be viewed here https://python-markdown.github.io/extensions/
